### ISSUE TITLE
Automation for Windows users

### ISSUE THREAD

**Issue by Telsenome** [RobinJ1995/gopro-cloud-media-downloader#3]
The example in the README doesn't work for Windows, but this one does. Thought it could be useful to add it to the README :-)

`$env:GOPRO_ACCOUNT_EMAIL="me@example.org" ; $env:GOPRO_ACCOUNT_PASSWORD="super_secret" ; $env:SCAN_LOCAL_DIR="C:\Users\robin\Pictures" ; node main.js`

**Comment by RobinJ1995** [comment]
I'd say since it's possible to just enter these without using environment variables this is not an issue. I'd expect anyone who runs Node.js scripts off Github to be able to figure out how to set environment variables if they use Windows, I'd say Linux or something with a proper shell is generally the expectation for scripts like these anyway.

**Comment by Telsenome** [comment]
Reasonable 👍
